version: '3.8'

# =====================================================
# 2Sweety Production Stack
# =====================================================
# Complete dating platform with frontend, backend, and database
# For Coolify deployment
# =====================================================

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: 2sweety-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-dating_db}
      MYSQL_USER: ${DB_USER:-dating_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mobile-app/Gommet Database 1.5/Gomeet.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - 2sweety-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=256M
      - --innodb_buffer_pool_size=512M
      - --innodb_log_file_size=128M

  # PHP Backend API
  backend:
    build:
      context: ./Gomeet Admin Panel 1.5
      dockerfile: Dockerfile
    container_name: 2sweety-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-dating_db}
      DB_USER: ${DB_USER:-dating_user}
      DB_PASSWORD: ${DB_PASSWORD}

      # API Configuration
      API_BASE_URL: ${API_BASE_URL:-https://api.2sweety.com}

      # Firebase Admin SDK (for server-side Firebase operations)
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-sweet-a6718}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}

      # Payment Gateway Keys (Server-side)
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_SECRET: ${PAYPAL_SECRET}

      # OneSignal for Push Notifications
      ONESIGNAL_APP_ID: ${ONESIGNAL_APP_ID:-94b2b6c5-fabb-4454-a2b7-75cf75b84789}
      ONESIGNAL_REST_API_KEY: ${ONESIGNAL_REST_API_KEY}

      # Agora for Video/Audio Calls
      AGORA_APP_ID: ${AGORA_APP_ID}
      AGORA_APP_CERTIFICATE: ${AGORA_APP_CERTIFICATE}

      # Security
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}

    volumes:
      - backend_uploads:/var/www/html/images
      - backend_logs:/var/log/apache2
    ports:
      - "8080:80"
    networks:
      - 2sweety-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend (Web App)
  frontend:
    build:
      context: ./GoMeet Web
      dockerfile: Dockerfile
      args:
        # Build-time environment variables
        REACT_APP_NAME: 2Sweety
        REACT_APP_VERSION: 1.0.0
        REACT_APP_ENVIRONMENT: production

        # API URLs
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-https://api.2sweety.com/api/}
        REACT_APP_IMAGE_BASE_URL: ${REACT_APP_IMAGE_BASE_URL:-https://api.2sweety.com/}
        REACT_APP_PAYMENT_BASE_URL: ${REACT_APP_PAYMENT_BASE_URL:-https://api.2sweety.com/}

        # Firebase Config
        REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN:-sweet-a6718.firebaseapp.com}
        REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID:-sweet-a6718}
        REACT_APP_FIREBASE_STORAGE_BUCKET: ${REACT_APP_FIREBASE_STORAGE_BUCKET:-sweet-a6718.firebasestorage.app}
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
        REACT_APP_FIREBASE_APP_ID: ${REACT_APP_FIREBASE_APP_ID}
        REACT_APP_FIREBASE_MEASUREMENT_ID: ${REACT_APP_FIREBASE_MEASUREMENT_ID}

        # Payment Gateway Keys (Client-side)
        REACT_APP_RAZORPAY_KEY_ID: ${REACT_APP_RAZORPAY_KEY_ID}
        REACT_APP_STRIPE_PUBLISHABLE_KEY: ${REACT_APP_STRIPE_PUBLISHABLE_KEY}
        REACT_APP_PAYPAL_CLIENT_ID: ${REACT_APP_PAYPAL_CLIENT_ID}

        # OneSignal
        REACT_APP_ONESIGNAL_APP_ID: ${REACT_APP_ONESIGNAL_APP_ID:-94b2b6c5-fabb-4454-a2b7-75cf75b84789}

        # Agora
        REACT_APP_AGORA_APP_ID: ${REACT_APP_AGORA_APP_ID}

        # Google Maps
        REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}

        # Feature Flags
        REACT_APP_ENABLE_VIDEO_CALL: ${REACT_APP_ENABLE_VIDEO_CALL:-true}
        REACT_APP_ENABLE_VOICE_CALL: ${REACT_APP_ENABLE_VOICE_CALL:-true}

    container_name: 2sweety-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - 2sweety-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional - for SSL termination)
  nginx:
    image: nginx:alpine
    container_name: 2sweety-nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - 2sweety-network
    profiles:
      - with-nginx

volumes:
  mysql_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local

networks:
  2sweety-network:
    driver: bridge

# =====================================================
# Environment Variables Required
# =====================================================
# Create a .env file with these variables:
#
# Database
# DB_ROOT_PASSWORD=your_root_password_here
# DB_NAME=dating_db
# DB_USER=dating_user
# DB_PASSWORD=your_db_password_here
#
# Firebase
# FIREBASE_PROJECT_ID=sweet-a6718
# FIREBASE_PRIVATE_KEY=your_firebase_private_key
# FIREBASE_CLIENT_EMAIL=your_firebase_client_email
# REACT_APP_FIREBASE_API_KEY=your_firebase_api_key
# REACT_APP_FIREBASE_MESSAGING_SENDER_ID=your_sender_id
# REACT_APP_FIREBASE_APP_ID=your_app_id
# REACT_APP_FIREBASE_MEASUREMENT_ID=your_measurement_id
#
# Payment Gateways
# RAZORPAY_KEY_ID=your_razorpay_key
# RAZORPAY_KEY_SECRET=your_razorpay_secret
# STRIPE_SECRET_KEY=your_stripe_secret
# STRIPE_PUBLISHABLE_KEY=your_stripe_publishable
# PAYPAL_CLIENT_ID=your_paypal_client_id
# PAYPAL_SECRET=your_paypal_secret
#
# Push Notifications
# ONESIGNAL_APP_ID=94b2b6c5-fabb-4454-a2b7-75cf75b84789
# ONESIGNAL_REST_API_KEY=your_onesignal_rest_key
#
# Video Calls
# AGORA_APP_ID=your_agora_app_id
# AGORA_APP_CERTIFICATE=your_agora_certificate
#
# Security
# JWT_SECRET=your_jwt_secret_key_min_32_chars
# API_KEY=your_api_key_for_backend
#
# URLs
# API_BASE_URL=https://api.2sweety.com
# REACT_APP_API_BASE_URL=https://api.2sweety.com/api/
# REACT_APP_IMAGE_BASE_URL=https://api.2sweety.com/
#
# =====================================================
