/* jshint esversion: 6 */
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      home: 'Home',
      about: 'About Us',
      contact: 'Contact Us',
      details: 'Details Page',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Log Out",
      "Account & Security": "Account & Security",
      "Buy Coin": "Buy Coin",
      "Explore": "Explore",
      "Settings": "Settings",
      "Wallet": "Wallet",
      "Edit": "Edit",
      "You're Activated Membersip": "Your Membership is Activated",
      "Active": "Active",
      "Enjoy premium and match anyway": "Enjoy premium and match anyway",
      "Is Verify": "Is Verified",
      "Panding": "Pending",
      "Upload Photo": "Upload Photo",
      "persons Online": "persons Online",
      "There are": "There are",
      "Loading...": "Loading...",
      "Filter": "Filter",
      "Premium": "Premium",
      "Upgrade Now": "Upgrade Now",
      "Apply": "Apply",
      "Add": "Add",
      "Add Your Favorite Photo": "Add Your Favorite Photo",
      "Upload": "Upload",
      "shortly": "shortly",
      "selfies and will get back to you": "selfies and will get back to you",
      "We are currently reviewing your": "We are currently reviewing your",
      "Review": "Review",
      "Verification Under": "Verification Under",
      "No Any Passed Profiles...": "No Passed Profiles...",
      "No Add Any Favourite Profiles...": "No Favorite Profiles Added...",
      "No Any User Like You...": "No Users Like You...",
      "No Any Match Profiles...": "No Match Profiles...",
      "Passed": "Passed",
      "Favourite": "Favorite",
      "Like Me": "Like Me",
      "New Match": "New Match",
      "Filter & Show": "Filter & Show",
      "Verify Profile": "Verify Profile",
      "Distance Range": "Distance Range",
      "Age": "Age",
      "Serach Preference": "Search Preference",
      "Interests": "Interests",
      "Langusges I Know": "Languages I Know",
      "Religion": "Religion",
      "Relationship Goals": "Relationship Goals",
      "Update": "Update",
      "Distance Preference": "Distance Preference",
      "Birthdate": "Birthdate",
      "Password": "Password",
      "Mobile Number": "Mobile Number",
      "Email": "Email",
      "Nick Name": "Nickname",
      "Update your personal photos here.": "Update your personal photos here.",
      "Height": "Height",
      "CM": "CM",
      "Bio": "Bio",
      "Gender": "Gender",
      "No any Transaction...": "No Transactions...",
      "Transaction": "Transaction",
      "Top-up": "Top-up",
      "Total Balance": "Total Balance",
      "Coin Buying & Info": "Coin Buying & Info",
      "Withdraw": "Withdraw",
      "Select Coin Package": "Select Coin Package",
      "History": "History",
      "Your Coin": "Your Coins",
      "Coins cannot be transferred to any users...": "Coins cannot be transferred to any users...",
      "Coins can be withdrawn eith the described method only...": "Coins can be withdrawn with the described method only...",
      "Coins are credited to your Coin balance only...": "Coins are credited to your Coin balance only...",
      "Coins can be used with all payment modes...": "Coins can be used with all payment modes...",
      "Coins don't have any expiry date...": "Coins don't have any expiry date...",
      "Coin can be used for sending gifts only...": "Coins can be used for sending gifts only...",
      "You need a minimum of 1000 coins to make a withdeawal...": "You need a minimum of 1000 coins to make a withdrawal...",
      "The pepole you blocked are displayed here..": "The people you blocked are displayed here.",
      "Blocked Users": "Blocked Users",
      "Get Started": "Get Started",
      "Plans": "Plans",
      "Number Of Coin": "Number of Coins",
      "Paypal": "PayPal",
      "BANK Transfer": "Bank Transfer",
      "Proceed": "Proceed",
      "Please Email ID": "Please Enter Email ID",
      "Email ID": "Email ID",
      "Please Enter IFSC Code": "Please Enter IFSC Code",
      "IFSC Code": "IFSC Code",
      "Please Enter Account Holder Name": "Please Enter Account Holder Name",
      "Account Holder Name": "Account Holder Name",
      "Please Enter Bank Name": "Please Enter Bank Name",
      "Bank Name": "Bank Name",
      "Please Enter Account Number": "Please Enter Account Number",
      "Account Number": "Account Number",
      "Please Enter UPI": "Please Enter UPI",
      "UPI": "UPI",
      "Select Type": "Select Type",
      "Please Enter Amount": "Please Enter Amount",
      "Coin History": "Coin History",
      "Withdraw History": "Withdraw History",
      "Yes, Block": "Yes, Block",
      "Cancel": "Cancel",
      "You can unblock them anytime in Settings.": "You can unblock them anytime in Settings.",
      "They will not be notified if you block them.": "They will not be notified if you block them.",
      "They will not be able to find your profile and send you messages.": "They will not be able to find your profile and send you messages.",
      "Acchcuu. Don't worry we won't tell them..": "Don't worry, we won't tell them.",
      "Please tell us why you are blocking": "Please tell us why you are blocking",
      "Blocking": "Blocking",
      "Languages": "Languages",
      "Block": "Block",
      "Report": "Report",
      "Continue": "Continue",
      "Why did you report this user?": "Why did you report this user?",
      "Don't worry we won't tell them": "Don't worry, we won't tell them",
      "Please tell us why you are reporting": "Please tell us why you are reporting",
      "Reporting": "Reporting",
      "Send Gifts": "Send Gifts",
      "Request Date": "Request Date",
      "Ifsc Code": "IFSC Code",
      "Account Name": "Account Name",
      "pay by": "Pay by",
      "Amount": "Amount",
      "Number of coin": "Number of Coins",
      "Payout id": "Payout ID",
      "User Chat": "User Chat",
      "Messages": "Messages",
      "Online now": "Online now",
      "Select User": "Select User",
      "Offline": "Offline",
      "online": "online",
      "No Any Match Profile...": "No Match Profiles...",
      "Reset": "Reset",
      "No Any New Profile...": "No New Profiles...",
      "Start Your Search for the Perfect Partner": "Start Your Search for the Perfect Partner",
      "Under Review": "Under Review",
      "Unverified": "Unverified",
    }
  },
  sv: {
    translation: {
      home: 'Hem',
      about: 'Om oss',
      contact: 'Kontakta oss',
      details: 'Detaljsida',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Logga ut",
      "Account & Security": "Konto & Säkerhet",
      "Buy Coin": "Köp Mynt",
      "Explore": "Utforska",
      "Settings": "Inställningar",
      "Wallet": "Plånbok",
      "Edit": "Redigera",
      "You're Activated Membersip": "Ditt medlemskap är aktiverat",
      "Active": "Aktiv",
      "Enjoy premium and match anyway": "Njut av premium och matcha ändå",
      "Is Verify": "Är verifierad",
      "Panding": "Väntar",
      "Upload Photo": "Ladda upp foto",
      "persons Online": "personer online",
      "There are": "Det finns",
      "Loading...": "Laddar...",
      "Filter": "Filter",
      "Premium": "Premium",
      "Upgrade Now": "Uppgradera nu",
      "Apply": "Tillämpa",
      "Add": "Lägg till",
      "Add Your Favorite Photo": "Lägg till din favoritbild",
      "Upload": "Ladda upp",
      "shortly": "inom kort",
      "selfies and will get back to you": "selfies och vi återkommer till dig",
      "We are currently reviewing your": "Vi granskar för närvarande dina",
      "Review": "Granskning",
      "Verification Under": "Verifiering pågår",
      "No Any Passed Profiles...": "Inga godkända profiler...",
      "No Add Any Favourite Profiles...": "Inga favoritprofiler tillagda...",
      "No Any User Like You...": "Ingen användare gillar dig...",
      "No Any Match Profiles...": "Inga matchande profiler...",
      "Passed": "Godkänd",
      "Favourite": "Favorit",
      "Like Me": "Gillar mig",
      "New Match": "Ny matchning",
      "Filter & Show": "Filtrera & visa",
      "Verify Profile": "Verifiera profil",
      "Distance Range": "Avståndsintervall",
      "Age": "Ålder",
      "Serach Preference": "Sökinställningar",
      "Interests": "Intressen",
      "Langusges I Know": "Språk jag kan",
      "Religion": "Religion",
      "Relationship Goals": "Relationsmål",
      "Update": "Uppdatera",
      "Distance Preference": "Avståndsinställning",
      "Birthdate": "Födelsedatum",
      "Password": "Lösenord",
      "Mobile Number": "Mobilnummer",
      "Email": "E-post",
      "Nick Name": "Smeknamn",
      "Update your personal photos here.": "Uppdatera dina personliga bilder här.",
      "Height": "Längd",
      "CM": "CM",
      "Bio": "Bio",
      "Gender": "Kön",
      "No any Transaction...": "Inga transaktioner...",
      "Transaction": "Transaktion",
      "Top-up": "Fyll på",
      "Total Balance": "Totalt saldo",
      "Coin Buying & Info": "Köp mynt & info",
      "Withdraw": "Ta ut",
      "Select Coin Package": "Välj myntpaket",
      "History": "Historik",
      "Your Coin": "Dina mynt",
      "Coins cannot be transferred to any users...": "Mynt kan inte överföras till andra användare...",
      "Coins can be withdrawn eith the described method only...": "Mynt kan endast tas ut med beskriven metod...",
      "Coins are credited to your Coin balance only...": "Mynt krediteras endast till ditt myntsaldo...",
      "Coins can be used with all payment modes...": "Mynt kan användas med alla betalningsmetoder...",
      "Coins don't have any expiry date...": "Mynt har inget utgångsdatum...",
      "Coin can be used for sending gifts only...": "Mynt kan endast användas för att skicka presenter...",
      "You need a minimum of 1000 coins to make a withdeawal...": "Du behöver minst 1000 mynt för att göra ett uttag...",
      "The pepole you blocked are displayed here..": "Personerna du blockerat visas här.",
      "Blocked Users": "Blockerade användare",
      "Get Started": "Kom igång",
      "Plans": "Planer",
      "Number Of Coin": "Antal mynt",
      "Paypal": "PayPal",
      "BANK Transfer": "Banköverföring",
      "Proceed": "Fortsätt",
      "Please Email ID": "Ange e-post-ID",
      "Email ID": "E-post-ID",
      "Please Enter IFSC Code": "Ange IFSC-kod",
      "IFSC Code": "IFSC-kod",
      "Please Enter Account Holder Name": "Ange kontoinnehavarens namn",
      "Account Holder Name": "Kontoinnehavarens namn",
      "Please Enter Bank Name": "Ange banknamn",
      "Bank Name": "Banknamn",
      "Please Enter Account Number": "Ange kontonummer",
      "Account Number": "Kontonummer",
      "Please Enter UPI": "Ange UPI",
      "UPI": "UPI",
      "Select Type": "Välj typ",
      "Please Enter Amount": "Ange belopp",
      "Coin History": "Mynthistorik",
      "Withdraw History": "Uttagshistorik",
      "Yes, Block": "Ja, blockera",
      "Cancel": "Avbryt",
      "You can unblock them anytime in Settings.": "Du kan avblockera dem när som helst i Inställningar.",
      "They will not be notified if you block them.": "De kommer inte att meddelas om du blockerar dem.",
      "They will not be able to find your profile and send you messages.": "De kommer inte att kunna hitta din profil och skicka meddelanden till dig.",
      "Acchcuu. Don't worry we won't tell them..": "Oroa dig inte, vi berättar inte för dem.",
      "Please tell us why you are blocking": "Berätta varför du blockerar",
      "Blocking": "Blockerar",
      "Languages": "Språk",
      "Block": "Blockera",
      "Report": "Rapportera",
      "Continue": "Fortsätt",
      "Why did you report this user?": "Varför rapporterade du denna användare?",
      "Don't worry we won't tell them": "Oroa dig inte, vi berättar inte för dem",
      "Please tell us why you are reporting": "Berätta varför du rapporterar",
      "Reporting": "Rapporterar",
      "Send Gifts": "Skicka presenter",
      "Request Date": "Begärandedatum",
      "Ifsc Code": "IFSC-kod",
      "Account Name": "Kontonamn",
      "pay by": "betala med",
      "Amount": "Belopp",
      "Number of coin": "Antal mynt",
      "Payout id": "Utbetalnings-ID",
      "User Chat": "Användarchatt",
      "Messages": "Meddelanden",
      "Online now": "Online nu",
      "Select User": "Välj användare",
      "Offline": "Offline",
      "online": "online",
      "No Any Match Profile...": "Inga matchande profiler...",
      "Reset": "Återställ",
      "No Any New Profile...": "Inga nya profiler...",
      "Start Your Search for the Perfect Partner": "Börja din sökning efter den perfekta partnern",
      "Under Review": "Under granskning",
      "Unverified": "Overifierad",
    }
  },
  no: {
    translation: {
      home: 'Hjem',
      about: 'Om oss',
      contact: 'Kontakt oss',
      details: 'Detaljside',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Logg ut",
      "Account & Security": "Konto & Sikkerhet",
      "Buy Coin": "Kjøp Mynter",
      "Explore": "Utforsk",
      "Settings": "Innstillinger",
      "Wallet": "Lommebok",
      "Edit": "Rediger",
      "You're Activated Membersip": "Ditt medlemskap er aktivert",
      "Active": "Aktiv",
      "Enjoy premium and match anyway": "Nyt premium og match uansett",
      "Is Verify": "Er verifisert",
      "Panding": "Venter",
      "Upload Photo": "Last opp bilde",
      "persons Online": "personer online",
      "There are": "Det er",
      "Loading...": "Laster...",
      "Filter": "Filter",
      "Premium": "Premium",
      "Upgrade Now": "Oppgrader nå",
      "Apply": "Bruk",
      "Add": "Legg til",
      "Add Your Favorite Photo": "Legg til favorittbildet ditt",
      "Upload": "Last opp",
      "shortly": "snart",
      "selfies and will get back to you": "selfier og vi kommer tilbake til deg",
      "We are currently reviewing your": "Vi gjennomgår for tiden dine",
      "Review": "Gjennomgang",
      "Verification Under": "Verifisering pågår",
      "No Any Passed Profiles...": "Ingen godkjente profiler...",
      "No Add Any Favourite Profiles...": "Ingen favorittprofiler lagt til...",
      "No Any User Like You...": "Ingen brukere liker deg...",
      "No Any Match Profiles...": "Ingen matchende profiler...",
      "Passed": "Godkjent",
      "Favourite": "Favoritt",
      "Like Me": "Liker meg",
      "New Match": "Ny match",
      "Filter & Show": "Filtrer og vis",
      "Verify Profile": "Verifiser profil",
      "Distance Range": "Avstandsområde",
      "Age": "Alder",
      "Serach Preference": "Søkepreferanse",
      "Interests": "Interesser",
      "Langusges I Know": "Språk jeg kan",
      "Religion": "Religion",
      "Relationship Goals": "Relasjonsmål",
      "Update": "Oppdater",
      "Distance Preference": "Avstandspreferanse",
      "Birthdate": "Fødselsdato",
      "Password": "Passord",
      "Mobile Number": "Mobilnummer",
      "Email": "E-post",
      "Nick Name": "Kallenavn",
      "Update your personal photos here.": "Oppdater dine personlige bilder her.",
      "Height": "Høyde",
      "CM": "CM",
      "Bio": "Bio",
      "Gender": "Kjønn",
      "No any Transaction...": "Ingen transaksjoner...",
      "Transaction": "Transaksjon",
      "Top-up": "Fyll på",
      "Total Balance": "Total saldo",
      "Coin Buying & Info": "Kjøp mynter & info",
      "Withdraw": "Ta ut",
      "Select Coin Package": "Velg myntpakke",
      "History": "Historikk",
      "Your Coin": "Dine mynter",
      "Coins cannot be transferred to any users...": "Mynter kan ikke overføres til andre brukere...",
      "Coins can be withdrawn eith the described method only...": "Mynter kan kun tas ut med beskrevet metode...",
      "Coins are credited to your Coin balance only...": "Mynter krediteres kun til din myntsaldo...",
      "Coins can be used with all payment modes...": "Mynter kan brukes med alle betalingsmetoder...",
      "Coins don't have any expiry date...": "Mynter har ingen utløpsdato...",
      "Coin can be used for sending gifts only...": "Mynter kan kun brukes til å sende gaver...",
      "You need a minimum of 1000 coins to make a withdeawal...": "Du trenger minimum 1000 mynter for å gjøre et uttak...",
      "The pepole you blocked are displayed here..": "Personene du har blokkert vises her.",
      "Blocked Users": "Blokkerte brukere",
      "Get Started": "Kom i gang",
      "Plans": "Planer",
      "Number Of Coin": "Antall mynter",
      "Paypal": "PayPal",
      "BANK Transfer": "Bankoverføring",
      "Proceed": "Fortsett",
      "Please Email ID": "Vennligst oppgi e-post-ID",
      "Email ID": "E-post-ID",
      "Please Enter IFSC Code": "Vennligst oppgi IFSC-kode",
      "IFSC Code": "IFSC-kode",
      "Please Enter Account Holder Name": "Vennligst oppgi kontohaverens navn",
      "Account Holder Name": "Kontohaverens navn",
      "Please Enter Bank Name": "Vennligst oppgi banknavn",
      "Bank Name": "Banknavn",
      "Please Enter Account Number": "Vennligst oppgi kontonummer",
      "Account Number": "Kontonummer",
      "Please Enter UPI": "Vennligst oppgi UPI",
      "UPI": "UPI",
      "Select Type": "Velg type",
      "Please Enter Amount": "Vennligst oppgi beløp",
      "Coin History": "Mynthistorikk",
      "Withdraw History": "Uttakshistorikk",
      "Yes, Block": "Ja, blokker",
      "Cancel": "Avbryt",
      "You can unblock them anytime in Settings.": "Du kan fjerne blokkeringen når som helst i innstillinger.",
      "They will not be notified if you block them.": "De vil ikke bli varslet hvis du blokkerer dem.",
      "They will not be able to find your profile and send you messages.": "De vil ikke kunne finne profilen din og sende deg meldinger.",
      "Acchcuu. Don't worry we won't tell them..": "Ikke bekymre deg, vi forteller dem ikke.",
      "Please tell us why you are blocking": "Vennligst fortell oss hvorfor du blokkerer",
      "Blocking": "Blokkering",
      "Languages": "Språk",
      "Block": "Blokker",
      "Report": "Rapporter",
      "Continue": "Fortsett",
      "Why did you report this user?": "Hvorfor rapporterte du denne brukeren?",
      "Don't worry we won't tell them": "Ikke bekymre deg, vi forteller dem ikke",
      "Please tell us why you are reporting": "Vennligst fortell oss hvorfor du rapporterer",
      "Reporting": "Rapportering",
      "Send Gifts": "Send gaver",
      "Request Date": "Forespørselsdato",
      "Ifsc Code": "IFSC-kode",
      "Account Name": "Kontonavn",
      "pay by": "betal med",
      "Amount": "Beløp",
      "Number of coin": "Antall mynter",
      "Payout id": "Utbetalings-ID",
      "User Chat": "Brukerchat",
      "Messages": "Meldinger",
      "Online now": "Online nå",
      "Select User": "Velg bruker",
      "Offline": "Offline",
      "online": "online",
      "No Any Match Profile...": "Ingen matchende profiler...",
      "Reset": "Tilbakestill",
      "No Any New Profile...": "Ingen nye profiler...",
      "Start Your Search for the Perfect Partner": "Start søket etter den perfekte partneren",
      "Under Review": "Under gjennomgang",
      "Unverified": "Ikke verifisert",
    }
  },
  fi: {
    translation: {
      home: 'Etusivu',
      about: 'Meistä',
      contact: 'Ota yhteyttä',
      details: 'Tietosivu',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Kirjaudu ulos",
      "Account & Security": "Tili & Turvallisuus",
      "Buy Coin": "Osta Kolikoita",
      "Explore": "Selaa",
      "Settings": "Asetukset",
      "Wallet": "Lompakko",
      "Edit": "Muokkaa",
      "You're Activated Membersip": "Jäsenyytesi on aktivoitu",
      "Active": "Aktiivinen",
      "Enjoy premium and match anyway": "Nauti premiumista ja matchaa joka tapauksessa",
      "Is Verify": "On vahvistettu",
      "Panding": "Odottaa",
      "Upload Photo": "Lataa kuva",
      "persons Online": "henkilöä verkossa",
      "There are": "On",
      "Loading...": "Ladataan...",
      "Filter": "Suodata",
      "Premium": "Premium",
      "Upgrade Now": "Päivitä nyt",
      "Apply": "Käytä",
      "Add": "Lisää",
      "Add Your Favorite Photo": "Lisää suosikkikuvasi",
      "Upload": "Lataa",
      "shortly": "pian",
      "selfies and will get back to you": "selfieitä ja palaamme asiaan",
      "We are currently reviewing your": "Tarkistamme parhaillaan",
      "Review": "Tarkistus",
      "Verification Under": "Vahvistus käynnissä",
      "No Any Passed Profiles...": "Ei hyväksyttyjä profiileja...",
      "No Add Any Favourite Profiles...": "Ei lisättyjä suosikkiprofiileja...",
      "No Any User Like You...": "Kukaan ei pidä sinusta...",
      "No Any Match Profiles...": "Ei vastaavia profiileja...",
      "Passed": "Hyväksytty",
      "Favourite": "Suosikki",
      "Like Me": "Pitää minusta",
      "New Match": "Uusi match",
      "Filter & Show": "Suodata ja näytä",
      "Verify Profile": "Vahvista profiili",
      "Distance Range": "Etäisyysalue",
      "Age": "Ikä",
      "Serach Preference": "Hakuasetukset",
      "Interests": "Kiinnostuksen kohteet",
      "Langusges I Know": "Osaamani kielet",
      "Religion": "Uskonto",
      "Relationship Goals": "Suhdetavoitteet",
      "Update": "Päivitä",
      "Distance Preference": "Etäisyysasetus",
      "Birthdate": "Syntymäaika",
      "Password": "Salasana",
      "Mobile Number": "Matkapuhelinnumero",
      "Email": "Sähköposti",
      "Nick Name": "Lempinimi",
      "Update your personal photos here.": "Päivitä henkilökohtaiset kuvasi täällä.",
      "Height": "Pituus",
      "CM": "CM",
      "Bio": "Bio",
      "Gender": "Sukupuoli",
      "No any Transaction...": "Ei tapahtumia...",
      "Transaction": "Tapahtuma",
      "Top-up": "Lataa",
      "Total Balance": "Kokonaissaldo",
      "Coin Buying & Info": "Osta kolikoita & tiedot",
      "Withdraw": "Nosta",
      "Select Coin Package": "Valitse kolikkopaketti",
      "History": "Historia",
      "Your Coin": "Sinun kolikot",
      "Coins cannot be transferred to any users...": "Kolikoita ei voi siirtää muille käyttäjille...",
      "Coins can be withdrawn eith the described method only...": "Kolikot voidaan nostaa vain kuvatulla menetelmällä...",
      "Coins are credited to your Coin balance only...": "Kolikot hyvitetään vain kolikkosaldollesi...",
      "Coins can be used with all payment modes...": "Kolikoita voi käyttää kaikilla maksutavoilla...",
      "Coins don't have any expiry date...": "Kolikoilla ei ole vanhentumispäivää...",
      "Coin can be used for sending gifts only...": "Kolikoita voi käyttää vain lahjojen lähettämiseen...",
      "You need a minimum of 1000 coins to make a withdeawal...": "Tarvitset vähintään 1000 kolikkoa nostaaksesi...",
      "The pepole you blocked are displayed here..": "Estämäsi ihmiset näytetään täällä.",
      "Blocked Users": "Estetyt käyttäjät",
      "Get Started": "Aloita",
      "Plans": "Suunnitelmat",
      "Number Of Coin": "Kolikoiden määrä",
      "Paypal": "PayPal",
      "BANK Transfer": "Pankkisiirto",
      "Proceed": "Jatka",
      "Please Email ID": "Anna sähköpostitunnus",
      "Email ID": "Sähköpostitunnus",
      "Please Enter IFSC Code": "Anna IFSC-koodi",
      "IFSC Code": "IFSC-koodi",
      "Please Enter Account Holder Name": "Anna tilinomistajan nimi",
      "Account Holder Name": "Tilinomistajan nimi",
      "Please Enter Bank Name": "Anna pankin nimi",
      "Bank Name": "Pankin nimi",
      "Please Enter Account Number": "Anna tilinumero",
      "Account Number": "Tilinumero",
      "Please Enter UPI": "Anna UPI",
      "UPI": "UPI",
      "Select Type": "Valitse tyyppi",
      "Please Enter Amount": "Anna summa",
      "Coin History": "Kolikkhistoria",
      "Withdraw History": "Nostohistoria",
      "Yes, Block": "Kyllä, estä",
      "Cancel": "Peruuta",
      "You can unblock them anytime in Settings.": "Voit poistaa eston milloin tahansa Asetuksissa.",
      "They will not be notified if you block them.": "Heitä ei ilmoiteta, jos estät heidät.",
      "They will not be able to find your profile and send you messages.": "He eivät voi löytää profiiliasi eivätkä lähettää sinulle viestejä.",
      "Acchcuu. Don't worry we won't tell them..": "Älä huoli, emme kerro heille.",
      "Please tell us why you are blocking": "Kerro meille, miksi estät",
      "Blocking": "Estäminen",
      "Languages": "Kielet",
      "Block": "Estä",
      "Report": "Raportoi",
      "Continue": "Jatka",
      "Why did you report this user?": "Miksi raportoit tämän käyttäjän?",
      "Don't worry we won't tell them": "Älä huoli, emme kerro heille",
      "Please tell us why you are reporting": "Kerro meille, miksi raportoit",
      "Reporting": "Raportointi",
      "Send Gifts": "Lähetä lahjoja",
      "Request Date": "Pyyntöpäivä",
      "Ifsc Code": "IFSC-koodi",
      "Account Name": "Tilin nimi",
      "pay by": "maksa",
      "Amount": "Summa",
      "Number of coin": "Kolikoiden määrä",
      "Payout id": "Maksutunnus",
      "User Chat": "Käyttäjäkeskustelu",
      "Messages": "Viestit",
      "Online now": "Online nyt",
      "Select User": "Valitse käyttäjä",
      "Offline": "Offline",
      "online": "online",
      "No Any Match Profile...": "Ei vastaavia profiileja...",
      "Reset": "Nollaa",
      "No Any New Profile...": "Ei uusia profiileja...",
      "Start Your Search for the Perfect Partner": "Aloita hakusi täydelliselle kumppanille",
      "Under Review": "Tarkistettavana",
      "Unverified": "Vahvistamaton",
    }
  },
  da: {
    translation: {
      home: 'Hjem',
      about: 'Om os',
      contact: 'Kontakt os',
      details: 'Detaljeside',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Log ud",
      "Account & Security": "Konto & Sikkerhed",
      "Buy Coin": "Køb Mønter",
      "Explore": "Udforsk",
      "Settings": "Indstillinger",
      "Wallet": "Tegnebog",
      "Edit": "Rediger",
      "You're Activated Membersip": "Dit medlemskab er aktiveret",
      "Active": "Aktiv",
      "Enjoy premium and match anyway": "Nyd premium og match alligevel",
      "Is Verify": "Er verificeret",
      "Panding": "Afventer",
      "Upload Photo": "Upload billede",
      "persons Online": "personer online",
      "There are": "Der er",
      "Loading...": "Indlæser...",
      "Filter": "Filter",
      "Premium": "Premium",
      "Upgrade Now": "Opgrader nu",
      "Apply": "Anvend",
      "Add": "Tilføj",
      "Add Your Favorite Photo": "Tilføj dit favoritbillede",
      "Upload": "Upload",
      "shortly": "snart",
      "selfies and will get back to you": "selfies, og vi vender tilbage til dig",
      "We are currently reviewing your": "Vi gennemgår i øjeblikket dine",
      "Review": "Gennemgang",
      "Verification Under": "Verificering i gang",
      "No Any Passed Profiles...": "Ingen godkendte profiler...",
      "No Add Any Favourite Profiles...": "Ingen favoritprofiler tilføjet...",
      "No Any User Like You...": "Ingen brugere kan lide dig...",
      "No Any Match Profiles...": "Ingen matchende profiler...",
      "Passed": "Godkendt",
      "Favourite": "Favorit",
      "Like Me": "Kan lide mig",
      "New Match": "Nyt match",
      "Filter & Show": "Filtrer og vis",
      "Verify Profile": "Verificer profil",
      "Distance Range": "Afstandsområde",
      "Age": "Alder",
      "Serach Preference": "Søgepræference",
      "Interests": "Interesser",
      "Langusges I Know": "Sprog jeg kan",
      "Religion": "Religion",
      "Relationship Goals": "Relationsmål",
      "Update": "Opdater",
      "Distance Preference": "Afstandspræference",
      "Birthdate": "Fødselsdato",
      "Password": "Adgangskode",
      "Mobile Number": "Mobilnummer",
      "Email": "E-mail",
      "Nick Name": "Kaldenavn",
      "Update your personal photos here.": "Opdater dine personlige billeder her.",
      "Height": "Højde",
      "CM": "CM",
      "Bio": "Bio",
      "Gender": "Køn",
      "No any Transaction...": "Ingen transaktioner...",
      "Transaction": "Transaktion",
      "Top-up": "Fyld op",
      "Total Balance": "Total saldo",
      "Coin Buying & Info": "Køb mønter & info",
      "Withdraw": "Hæv",
      "Select Coin Package": "Vælg møntpakke",
      "History": "Historik",
      "Your Coin": "Dine mønter",
      "Coins cannot be transferred to any users...": "Mønter kan ikke overføres til andre brugere...",
      "Coins can be withdrawn eith the described method only...": "Mønter kan kun hæves med den beskrevne metode...",
      "Coins are credited to your Coin balance only...": "Mønter krediteres kun til din møntsaldo...",
      "Coins can be used with all payment modes...": "Mønter kan bruges med alle betalingsmetoder...",
      "Coins don't have any expiry date...": "Mønter har ingen udløbsdato...",
      "Coin can be used for sending gifts only...": "Mønter kan kun bruges til at sende gaver...",
      "You need a minimum of 1000 coins to make a withdeawal...": "Du skal bruge mindst 1000 mønter for at foretage en hævning...",
      "The pepole you blocked are displayed here..": "De personer, du har blokeret, vises her.",
      "Blocked Users": "Blokerede brugere",
      "Get Started": "Kom i gang",
      "Plans": "Planer",
      "Number Of Coin": "Antal mønter",
      "Paypal": "PayPal",
      "BANK Transfer": "Bankoverførsel",
      "Proceed": "Fortsæt",
      "Please Email ID": "Indtast venligst e-mail-ID",
      "Email ID": "E-mail-ID",
      "Please Enter IFSC Code": "Indtast venligst IFSC-kode",
      "IFSC Code": "IFSC-kode",
      "Please Enter Account Holder Name": "Indtast venligst kontohaverens navn",
      "Account Holder Name": "Kontohaverens navn",
      "Please Enter Bank Name": "Indtast venligst banknavn",
      "Bank Name": "Banknavn",
      "Please Enter Account Number": "Indtast venligst kontonummer",
      "Account Number": "Kontonummer",
      "Please Enter UPI": "Indtast venligst UPI",
      "UPI": "UPI",
      "Select Type": "Vælg type",
      "Please Enter Amount": "Indtast venligst beløb",
      "Coin History": "Mønthistorik",
      "Withdraw History": "Hævningshistorik",
      "Yes, Block": "Ja, bloker",
      "Cancel": "Annuller",
      "You can unblock them anytime in Settings.": "Du kan fjerne blokeringen når som helst i Indstillinger.",
      "They will not be notified if you block them.": "De vil ikke blive underrettet, hvis du blokerer dem.",
      "They will not be able to find your profile and send you messages.": "De vil ikke kunne finde din profil og sende dig beskeder.",
      "Acchcuu. Don't worry we won't tell them..": "Bare rolig, vi fortæller dem det ikke.",
      "Please tell us why you are blocking": "Fortæl os venligst, hvorfor du blokerer",
      "Blocking": "Blokering",
      "Languages": "Sprog",
      "Block": "Bloker",
      "Report": "Rapporter",
      "Continue": "Fortsæt",
      "Why did you report this user?": "Hvorfor rapporterede du denne bruger?",
      "Don't worry we won't tell them": "Bare rolig, vi fortæller dem det ikke",
      "Please tell us why you are reporting": "Fortæl os venligst, hvorfor du rapporterer",
      "Reporting": "Rapportering",
      "Send Gifts": "Send gaver",
      "Request Date": "Anmodningsdato",
      "Ifsc Code": "IFSC-kode",
      "Account Name": "Kontonavn",
      "pay by": "betal med",
      "Amount": "Beløb",
      "Number of coin": "Antal mønter",
      "Payout id": "Udbetalings-ID",
      "User Chat": "Brugerchat",
      "Messages": "Beskeder",
      "Online now": "Online nu",
      "Select User": "Vælg bruger",
      "Offline": "Offline",
      "online": "online",
      "No Any Match Profile...": "Ingen matchende profiler...",
      "Reset": "Nulstil",
      "No Any New Profile...": "Ingen nye profiler...",
      "Start Your Search for the Perfect Partner": "Start din søgning efter den perfekte partner",
      "Under Review": "Under gennemgang",
      "Unverified": "Ikke verificeret",
    }
  },
  tr: {
    translation: {
      home: 'Ana Sayfa',
      about: 'Hakkımızda',
      contact: 'İletişim',
      details: 'Detay Sayfası',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Çıkış Yap",
      "Account & Security": "Hesap ve Güvenlik",
      "Buy Coin": "Jeton Satın Al",
      "Explore": "Keşfet",
      "Settings": "Ayarlar",
      "Wallet": "Cüzdan",
      "Edit": "Düzenle",
      "You're Activated Membersip": "Üyeliğiniz Aktif",
      "Active": "Aktif",
      "Enjoy premium and match anyway": "Premium'un keyfini çıkarın ve eşleşin",
      "Is Verify": "Doğrulandı",
      "Panding": "Beklemede",
      "Upload Photo": "Fotoğraf Yükle",
      "persons Online": "kişi çevrimiçi",
      "There are": "Şu anda",
      "Loading...": "Yükleniyor...",
      "Filter": "Filtre",
      "Premium": "Premium",
      "Upgrade Now": "Şimdi Yükselt",
      "Apply": "Uygula",
      "Add": "Ekle",
      "Add Your Favorite Photo": "Favori Fotoğrafınızı Ekleyin",
      "Upload": "Yükle",
      "shortly": "yakında",
      "selfies and will get back to you": "selfie'lerinizi inceliyoruz ve size geri döneceğiz",
      "We are currently reviewing your": "Şu anda inceliyoruz",
      "Review": "İnceleme",
      "Verification Under": "Doğrulama Devam Ediyor",
      "No Any Passed Profiles...": "Geçen Profil Yok...",
      "No Add Any Favourite Profiles...": "Favori Profil Eklenmedi...",
      "No Any User Like You...": "Sizi Beğenen Yok...",
      "No Any Match Profiles...": "Eşleşen Profil Yok...",
      "Passed": "Geçti",
      "Favourite": "Favori",
      "Like Me": "Beni Beğenenler",
      "New Match": "Yeni Eşleşme",
      "Filter & Show": "Filtrele ve Göster",
      "Verify Profile": "Profili Doğrula",
      "Distance Range": "Mesafe Aralığı",
      "Age": "Yaş",
      "Serach Preference": "Arama Tercihi",
      "Interests": "İlgi Alanları",
      "Langusges I Know": "Bildiğim Diller",
      "Religion": "Din",
      "Relationship Goals": "İlişki Hedefleri",
      "Update": "Güncelle",
      "Distance Preference": "Mesafe Tercihi",
      "Birthdate": "Doğum Tarihi",
      "Password": "Şifre",
      "Mobile Number": "Cep Telefonu",
      "Email": "E-posta",
      "Nick Name": "Takma Ad",
      "Update your personal photos here.": "Kişisel fotoğraflarınızı buradan güncelleyin.",
      "Height": "Boy",
      "CM": "CM",
      "Bio": "Biyografi",
      "Gender": "Cinsiyet",
      "No any Transaction...": "İşlem Yok...",
      "Transaction": "İşlem",
      "Top-up": "Yükle",
      "Total Balance": "Toplam Bakiye",
      "Coin Buying & Info": "Jeton Satın Alma ve Bilgi",
      "Withdraw": "Çek",
      "Select Coin Package": "Jeton Paketi Seç",
      "History": "Geçmiş",
      "Your Coin": "Jetonlarınız",
      "Coins cannot be transferred to any users...": "Jetonlar başka kullanıcılara aktarılamaz...",
      "Coins can be withdrawn eith the described method only...": "Jetonlar sadece belirtilen yöntemle çekilebilir...",
      "Coins are credited to your Coin balance only...": "Jetonlar sadece jeton bakiyenize yüklenir...",
      "Coins can be used with all payment modes...": "Jetonlar tüm ödeme yöntemleriyle kullanılabilir...",
      "Coins don't have any expiry date...": "Jetonların son kullanma tarihi yoktur...",
      "Coin can be used for sending gifts only...": "Jetonlar sadece hediye göndermek için kullanılabilir...",
      "You need a minimum of 1000 coins to make a withdeawal...": "Çekim yapmak için en az 1000 jetona ihtiyacınız var...",
      "The pepole you blocked are displayed here..": "Engellediğiniz kişiler burada görüntülenir.",
      "Blocked Users": "Engellenen Kullanıcılar",
      "Get Started": "Başlayın",
      "Plans": "Planlar",
      "Number Of Coin": "Jeton Sayısı",
      "Paypal": "PayPal",
      "BANK Transfer": "Banka Havalesi",
      "Proceed": "Devam Et",
      "Please Email ID": "Lütfen E-posta Kimliği Girin",
      "Email ID": "E-posta Kimliği",
      "Please Enter IFSC Code": "Lütfen IFSC Kodunu Girin",
      "IFSC Code": "IFSC Kodu",
      "Please Enter Account Holder Name": "Lütfen Hesap Sahibinin Adını Girin",
      "Account Holder Name": "Hesap Sahibinin Adı",
      "Please Enter Bank Name": "Lütfen Banka Adını Girin",
      "Bank Name": "Banka Adı",
      "Please Enter Account Number": "Lütfen Hesap Numarasını Girin",
      "Account Number": "Hesap Numarası",
      "Please Enter UPI": "Lütfen UPI Girin",
      "UPI": "UPI",
      "Select Type": "Tür Seçin",
      "Please Enter Amount": "Lütfen Tutarı Girin",
      "Coin History": "Jeton Geçmişi",
      "Withdraw History": "Çekim Geçmişi",
      "Yes, Block": "Evet, Engelle",
      "Cancel": "İptal",
      "You can unblock them anytime in Settings.": "Ayarlardan istediğiniz zaman engelini kaldırabilirsiniz.",
      "They will not be notified if you block them.": "Onları engellerseniz bildirim almayacaklar.",
      "They will not be able to find your profile and send you messages.": "Profilinizi bulamayacak ve size mesaj gönderemeyecekler.",
      "Acchcuu. Don't worry we won't tell them..": "Merak etmeyin, onlara söylemeyeceğiz.",
      "Please tell us why you are blocking": "Lütfen neden engellediğinizi bize bildirin",
      "Blocking": "Engelleme",
      "Languages": "Diller",
      "Block": "Engelle",
      "Report": "Şikayet Et",
      "Continue": "Devam Et",
      "Why did you report this user?": "Bu kullanıcıyı neden şikayet ettiniz?",
      "Don't worry we won't tell them": "Merak etmeyin, onlara söylemeyeceğiz",
      "Please tell us why you are reporting": "Lütfen neden şikayet ettiğinizi bize bildirin",
      "Reporting": "Şikayet Etme",
      "Send Gifts": "Hediye Gönder",
      "Request Date": "Talep Tarihi",
      "Ifsc Code": "IFSC Kodu",
      "Account Name": "Hesap Adı",
      "pay by": "Ödeme yöntemi",
      "Amount": "Tutar",
      "Number of coin": "Jeton sayısı",
      "Payout id": "Ödeme Kimliği",
      "User Chat": "Kullanıcı Sohbeti",
      "Messages": "Mesajlar",
      "Online now": "Şimdi çevrimiçi",
      "Select User": "Kullanıcı Seç",
      "Offline": "Çevrimdışı",
      "online": "çevrimiçi",
      "No Any Match Profile...": "Eşleşen Profil Yok...",
      "Reset": "Sıfırla",
      "No Any New Profile...": "Yeni Profil Yok...",
      "Start Your Search for the Perfect Partner": "Mükemmel Partneri Aramaya Başlayın",
      "Under Review": "İnceleniyor",
      "Unverified": "Doğrulanmamış",
    }
  },
  ar: {
    translation: {
      home: 'الرئيسية',
      about: 'من نحن',
      contact: 'اتصل بنا',
      details: 'صفحة التفاصيل',
      lorem: 'لوريم إيبسوم هو ببساطة نص شكلي يستخدم في صناعة الطباعة والتنضيد. كان لوريم إيبسوم هو النص الوهمي القياسي في الصناعة منذ القرن الخامس عشر الميلادي.',
      "Log Out": "تسجيل الخروج",
      "Account & Security": "الحساب والأمان",
      "Buy Coin": "شراء عملات",
      "Explore": "استكشف",
      "Settings": "الإعدادات",
      "Wallet": "المحفظة",
      "Edit": "تعديل",
      "You're Activated Membersip": "تم تفعيل عضويتك",
      "Active": "نشط",
      "Enjoy premium and match anyway": "استمتع بالعضوية المميزة وتواصل على أي حال",
      "Is Verify": "تم التحقق",
      "Panding": "قيد الانتظار",
      "Upload Photo": "تحميل صورة",
      "persons Online": "أشخاص متصلون",
      "There are": "يوجد",
      "Loading...": "جاري التحميل...",
      "Filter": "تصفية",
      "Premium": "مميز",
      "Upgrade Now": "الترقية الآن",
      "Apply": "تطبيق",
      "Add": "إضافة",
      "Add Your Favorite Photo": "أضف صورتك المفضلة",
      "Upload": "تحميل",
      "shortly": "قريباً",
      "selfies and will get back to you": "الصور الشخصية وسنعود إليك",
      "We are currently reviewing your": "نحن نراجع حالياً",
      "Review": "مراجعة",
      "Verification Under": "التحقق جارٍ",
      "No Any Passed Profiles...": "لا توجد ملفات شخصية تم تجاوزها...",
      "No Add Any Favourite Profiles...": "لم تتم إضافة ملفات شخصية مفضلة...",
      "No Any User Like You...": "لا يوجد مستخدمون يعجبون بك...",
      "No Any Match Profiles...": "لا توجد ملفات شخصية متطابقة...",
      "Passed": "تم التجاوز",
      "Favourite": "المفضلة",
      "Like Me": "يعجبني",
      "New Match": "تطابق جديد",
      "Filter & Show": "تصفية وعرض",
      "Verify Profile": "التحقق من الملف الشخصي",
      "Distance Range": "نطاق المسافة",
      "Age": "العمر",
      "Serach Preference": "تفضيلات البحث",
      "Interests": "الاهتمامات",
      "Langusges I Know": "اللغات التي أعرفها",
      "Religion": "الديانة",
      "Relationship Goals": "أهداف العلاقة",
      "Update": "تحديث",
      "Distance Preference": "تفضيل المسافة",
      "Birthdate": "تاريخ الميلاد",
      "Password": "كلمة المرور",
      "Mobile Number": "رقم الهاتف المحمول",
      "Email": "البريد الإلكتروني",
      "Nick Name": "الاسم المستعار",
      "Update your personal photos here.": "قم بتحديث صورك الشخصية هنا.",
      "Height": "الطول",
      "CM": "سم",
      "Bio": "السيرة الذاتية",
      "Gender": "الجنس",
      "No any Transaction...": "لا توجد معاملات...",
      "Transaction": "المعاملة",
      "Top-up": "إعادة شحن",
      "Total Balance": "الرصيد الإجمالي",
      "Coin Buying & Info": "شراء العملات والمعلومات",
      "Withdraw": "سحب",
      "Select Coin Package": "اختر حزمة العملات",
      "History": "السجل",
      "Your Coin": "عملاتك",
      "Coins cannot be transferred to any users...": "لا يمكن تحويل العملات إلى أي مستخدمين...",
      "Coins can be withdrawn eith the described method only...": "يمكن سحب العملات بالطريقة الموصوفة فقط...",
      "Coins are credited to your Coin balance only...": "يتم إضافة العملات إلى رصيد عملاتك فقط...",
      "Coins can be used with all payment modes...": "يمكن استخدام العملات مع جميع طرق الدفع...",
      "Coins don't have any expiry date...": "العملات ليس لها تاريخ انتهاء...",
      "Coin can be used for sending gifts only...": "يمكن استخدام العملات لإرسال الهدايا فقط...",
      "You need a minimum of 1000 coins to make a withdeawal...": "تحتاج إلى 1000 عملة كحد أدنى لإجراء سحب...",
      "The pepole you blocked are displayed here..": "يتم عرض الأشخاص الذين قمت بحظرهم هنا.",
      "Blocked Users": "المستخدمون المحظورون",
      "Get Started": "ابدأ",
      "Plans": "الخطط",
      "Number Of Coin": "عدد العملات",
      "Paypal": "باي بال",
      "BANK Transfer": "تحويل بنكي",
      "Proceed": "متابعة",
      "Please Email ID": "يرجى إدخال معرف البريد الإلكتروني",
      "Email ID": "معرف البريد الإلكتروني",
      "Please Enter IFSC Code": "يرجى إدخال رمز IFSC",
      "IFSC Code": "رمز IFSC",
      "Please Enter Account Holder Name": "يرجى إدخال اسم صاحب الحساب",
      "Account Holder Name": "اسم صاحب الحساب",
      "Please Enter Bank Name": "يرجى إدخال اسم البنك",
      "Bank Name": "اسم البنك",
      "Please Enter Account Number": "يرجى إدخال رقم الحساب",
      "Account Number": "رقم الحساب",
      "Please Enter UPI": "يرجى إدخال UPI",
      "UPI": "UPI",
      "Select Type": "اختر النوع",
      "Please Enter Amount": "يرجى إدخال المبلغ",
      "Coin History": "سجل العملات",
      "Withdraw History": "سجل السحب",
      "Yes, Block": "نعم، احظر",
      "Cancel": "إلغاء",
      "You can unblock them anytime in Settings.": "يمكنك إلغاء حظرهم في أي وقت في الإعدادات.",
      "They will not be notified if you block them.": "لن يتم إخطارهم إذا قمت بحظرهم.",
      "They will not be able to find your profile and send you messages.": "لن يتمكنوا من العثور على ملفك الشخصي وإرسال رسائل إليك.",
      "Acchcuu. Don't worry we won't tell them..": "لا تقلق، لن نخبرهم.",
      "Please tell us why you are blocking": "يرجى إخبارنا لماذا تقوم بالحظر",
      "Blocking": "الحظر",
      "Languages": "اللغات",
      "Block": "حظر",
      "Report": "تقرير",
      "Continue": "متابعة",
      "Why did you report this user?": "لماذا أبلغت عن هذا المستخدم؟",
      "Don't worry we won't tell them": "لا تقلق، لن نخبرهم",
      "Please tell us why you are reporting": "يرجى إخبارنا لماذا تقوم بالإبلاغ",
      "Reporting": "الإبلاغ",
      "Send Gifts": "إرسال هدايا",
      "Request Date": "تاريخ الطلب",
      "Ifsc Code": "رمز IFSC",
      "Account Name": "اسم الحساب",
      "pay by": "الدفع بواسطة",
      "Amount": "المبلغ",
      "Number of coin": "عدد العملات",
      "Payout id": "معرف الدفع",
      "User Chat": "دردشة المستخدم",
      "Messages": "الرسائل",
      "Online now": "متصل الآن",
      "Select User": "اختر مستخدم",
      "Offline": "غير متصل",
      "online": "متصل",
      "No Any Match Profile...": "لا توجد ملفات شخصية متطابقة...",
      "Reset": "إعادة تعيين",
      "No Any New Profile...": "لا توجد ملفات شخصية جديدة...",
      "Start Your Search for the Perfect Partner": "ابدأ البحث عن الشريك المثالي",
      "Under Review": "قيد المراجعة",
      "Unverified": "غير محقق",
    }
  },
  zh: {
    translation: {
      home: '首页',
      about: '关于我们',
      contact: '联系我们',
      details: '详情页',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "退出登录",
      "Account & Security": "账户与安全",
      "Buy Coin": "购买金币",
      "Explore": "探索",
      "Settings": "设置",
      "Wallet": "钱包",
      "Edit": "编辑",
      "You're Activated Membersip": "您的会员已激活",
      "Active": "活跃",
      "Enjoy premium and match anyway": "享受高级会员并随意匹配",
      "Is Verify": "已验证",
      "Panding": "待处理",
      "Upload Photo": "上传照片",
      "persons Online": "人在线",
      "There are": "有",
      "Loading...": "加载中...",
      "Filter": "筛选",
      "Premium": "高级会员",
      "Upgrade Now": "立即升级",
      "Apply": "应用",
      "Add": "添加",
      "Add Your Favorite Photo": "添加您最喜欢的照片",
      "Upload": "上传",
      "shortly": "很快",
      "selfies and will get back to you": "自拍照，我们会尽快回复您",
      "We are currently reviewing your": "我们正在审核您的",
      "Review": "审核",
      "Verification Under": "验证进行中",
      "No Any Passed Profiles...": "没有通过的个人资料...",
      "No Add Any Favourite Profiles...": "没有添加喜爱的个人资料...",
      "No Any User Like You...": "没有用户喜欢您...",
      "No Any Match Profiles...": "没有匹配的个人资料...",
      "Passed": "已通过",
      "Favourite": "收藏",
      "Like Me": "喜欢我",
      "New Match": "新匹配",
      "Filter & Show": "筛选并显示",
      "Verify Profile": "验证个人资料",
      "Distance Range": "距离范围",
      "Age": "年龄",
      "Serach Preference": "搜索偏好",
      "Interests": "兴趣",
      "Langusges I Know": "我知道的语言",
      "Religion": "宗教",
      "Relationship Goals": "关系目标",
      "Update": "更新",
      "Distance Preference": "距离偏好",
      "Birthdate": "出生日期",
      "Password": "密码",
      "Mobile Number": "手机号码",
      "Email": "邮箱",
      "Nick Name": "昵称",
      "Update your personal photos here.": "在此更新您的个人照片。",
      "Height": "身高",
      "CM": "厘米",
      "Bio": "简介",
      "Gender": "性别",
      "No any Transaction...": "没有交易记录...",
      "Transaction": "交易",
      "Top-up": "充值",
      "Total Balance": "总余额",
      "Coin Buying & Info": "金币购买与信息",
      "Withdraw": "提现",
      "Select Coin Package": "选择金币套餐",
      "History": "历史记录",
      "Your Coin": "您的金币",
      "Coins cannot be transferred to any users...": "金币无法转移给任何用户...",
      "Coins can be withdrawn eith the described method only...": "金币只能通过描述的方法提取...",
      "Coins are credited to your Coin balance only...": "金币仅记入您的金币余额...",
      "Coins can be used with all payment modes...": "金币可用于所有支付方式...",
      "Coins don't have any expiry date...": "金币没有有效期...",
      "Coin can be used for sending gifts only...": "金币只能用于赠送礼物...",
      "You need a minimum of 1000 coins to make a withdeawal...": "您需要至少1000金币才能提现...",
      "The pepole you blocked are displayed here..": "您屏蔽的人显示在这里。",
      "Blocked Users": "已屏蔽的用户",
      "Get Started": "开始",
      "Plans": "计划",
      "Number Of Coin": "金币数量",
      "Paypal": "PayPal",
      "BANK Transfer": "银行转账",
      "Proceed": "继续",
      "Please Email ID": "请输入邮箱ID",
      "Email ID": "邮箱ID",
      "Please Enter IFSC Code": "请输入IFSC代码",
      "IFSC Code": "IFSC代码",
      "Please Enter Account Holder Name": "请输入账户持有人姓名",
      "Account Holder Name": "账户持有人姓名",
      "Please Enter Bank Name": "请输入银行名称",
      "Bank Name": "银行名称",
      "Please Enter Account Number": "请输入账号",
      "Account Number": "账号",
      "Please Enter UPI": "请输入UPI",
      "UPI": "UPI",
      "Select Type": "选择类型",
      "Please Enter Amount": "请输入金额",
      "Coin History": "金币历史",
      "Withdraw History": "提现历史",
      "Yes, Block": "是的，屏蔽",
      "Cancel": "取消",
      "You can unblock them anytime in Settings.": "您可以随时在设置中取消屏蔽。",
      "They will not be notified if you block them.": "如果您屏蔽他们，他们不会收到通知。",
      "They will not be able to find your profile and send you messages.": "他们将无法找到您的个人资料并向您发送消息。",
      "Acchcuu. Don't worry we won't tell them..": "别担心，我们不会告诉他们。",
      "Please tell us why you are blocking": "请告诉我们您为什么要屏蔽",
      "Blocking": "屏蔽",
      "Languages": "语言",
      "Block": "屏蔽",
      "Report": "举报",
      "Continue": "继续",
      "Why did you report this user?": "您为什么举报此用户？",
      "Don't worry we won't tell them": "别担心，我们不会告诉他们",
      "Please tell us why you are reporting": "请告诉我们您为什么要举报",
      "Reporting": "举报",
      "Send Gifts": "发送礼物",
      "Request Date": "请求日期",
      "Ifsc Code": "IFSC代码",
      "Account Name": "账户名称",
      "pay by": "支付方式",
      "Amount": "金额",
      "Number of coin": "金币数量",
      "Payout id": "支付ID",
      "User Chat": "用户聊天",
      "Messages": "消息",
      "Online now": "现在在线",
      "Select User": "选择用户",
      "Offline": "离线",
      "online": "在线",
      "No Any Match Profile...": "没有匹配的个人资料...",
      "Reset": "重置",
      "No Any New Profile...": "没有新的个人资料...",
      "Start Your Search for the Perfect Partner": "开始寻找完美伴侣",
      "Under Review": "审核中",
      "Unverified": "未验证",
    }
  },
  fr: {
    translation: {
      home: 'Accueil',
      about: 'À propos de nous',
      contact: 'Contactez-nous',
      details: 'Page de détails',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Se déconnecter",
      "Account & Security": "Compte et sécurité",
      "Buy Coin": "Acheter des pièces",
      "Explore": "Explorer",
      "Settings": "Paramètres",
      "Wallet": "Portefeuille",
      "Edit": "Modifier",
      "You're Activated Membersip": "Votre adhésion est activée",
      "Active": "Actif",
      "Enjoy premium and match anyway": "Profitez du premium et trouvez des correspondances",
      "Is Verify": "Est vérifié",
      "Panding": "En attente",
      "Upload Photo": "Télécharger une photo",
      "persons Online": "personnes en ligne",
      "There are": "Il y a",
      "Loading...": "Chargement...",
      "Filter": "Filtrer",
      "Premium": "Premium",
      "Upgrade Now": "Mettre à niveau maintenant",
      "Apply": "Appliquer",
      "Add": "Ajouter",
      "Add Your Favorite Photo": "Ajoutez votre photo préférée",
      "Upload": "Télécharger",
      "shortly": "bientôt",
      "selfies and will get back to you": "selfies et nous reviendrons vers vous",
      "We are currently reviewing your": "Nous examinons actuellement vos",
      "Review": "Révision",
      "Verification Under": "Vérification en cours",
      "No Any Passed Profiles...": "Aucun profil validé...",
      "No Add Any Favourite Profiles...": "Aucun profil favori ajouté...",
      "No Any User Like You...": "Aucun utilisateur ne vous aime...",
      "No Any Match Profiles...": "Aucun profil correspondant...",
      "Passed": "Validé",
      "Favourite": "Favori",
      "Like Me": "M'aime",
      "New Match": "Nouvelle correspondance",
      "Filter & Show": "Filtrer et afficher",
      "Verify Profile": "Vérifier le profil",
      "Distance Range": "Plage de distance",
      "Age": "Âge",
      "Serach Preference": "Préférence de recherche",
      "Interests": "Centres d'intérêt",
      "Langusges I Know": "Langues que je connais",
      "Religion": "Religion",
      "Relationship Goals": "Objectifs relationnels",
      "Update": "Mettre à jour",
      "Distance Preference": "Préférence de distance",
      "Birthdate": "Date de naissance",
      "Password": "Mot de passe",
      "Mobile Number": "Numéro de mobile",
      "Email": "E-mail",
      "Nick Name": "Pseudo",
      "Update your personal photos here.": "Mettez à jour vos photos personnelles ici.",
      "Height": "Taille",
      "CM": "CM",
      "Bio": "Bio",
      "Gender": "Genre",
      "No any Transaction...": "Aucune transaction...",
      "Transaction": "Transaction",
      "Top-up": "Recharger",
      "Total Balance": "Solde total",
      "Coin Buying & Info": "Achat de pièces et infos",
      "Withdraw": "Retirer",
      "Select Coin Package": "Sélectionner un pack de pièces",
      "History": "Historique",
      "Your Coin": "Vos pièces",
      "Coins cannot be transferred to any users...": "Les pièces ne peuvent pas être transférées à d'autres utilisateurs...",
      "Coins can be withdrawn eith the described method only...": "Les pièces ne peuvent être retirées qu'avec la méthode décrite...",
      "Coins are credited to your Coin balance only...": "Les pièces sont créditées uniquement sur votre solde de pièces...",
      "Coins can be used with all payment modes...": "Les pièces peuvent être utilisées avec tous les modes de paiement...",
      "Coins don't have any expiry date...": "Les pièces n'ont pas de date d'expiration...",
      "Coin can be used for sending gifts only...": "Les pièces ne peuvent être utilisées que pour envoyer des cadeaux...",
      "You need a minimum of 1000 coins to make a withdeawal...": "Vous avez besoin d'un minimum de 1000 pièces pour effectuer un retrait...",
      "The pepole you blocked are displayed here..": "Les personnes que vous avez bloquées sont affichées ici.",
      "Blocked Users": "Utilisateurs bloqués",
      "Get Started": "Commencer",
      "Plans": "Plans",
      "Number Of Coin": "Nombre de pièces",
      "Paypal": "PayPal",
      "BANK Transfer": "Virement bancaire",
      "Proceed": "Continuer",
      "Please Email ID": "Veuillez entrer l'identifiant e-mail",
      "Email ID": "Identifiant e-mail",
      "Please Enter IFSC Code": "Veuillez entrer le code IFSC",
      "IFSC Code": "Code IFSC",
      "Please Enter Account Holder Name": "Veuillez entrer le nom du titulaire du compte",
      "Account Holder Name": "Nom du titulaire du compte",
      "Please Enter Bank Name": "Veuillez entrer le nom de la banque",
      "Bank Name": "Nom de la banque",
      "Please Enter Account Number": "Veuillez entrer le numéro de compte",
      "Account Number": "Numéro de compte",
      "Please Enter UPI": "Veuillez entrer UPI",
      "UPI": "UPI",
      "Select Type": "Sélectionner le type",
      "Please Enter Amount": "Veuillez entrer le montant",
      "Coin History": "Historique des pièces",
      "Withdraw History": "Historique des retraits",
      "Yes, Block": "Oui, bloquer",
      "Cancel": "Annuler",
      "You can unblock them anytime in Settings.": "Vous pouvez les débloquer à tout moment dans les paramètres.",
      "They will not be notified if you block them.": "Ils ne seront pas notifiés si vous les bloquez.",
      "They will not be able to find your profile and send you messages.": "Ils ne pourront pas trouver votre profil et vous envoyer des messages.",
      "Acchcuu. Don't worry we won't tell them..": "Ne vous inquiétez pas, nous ne leur dirons pas.",
      "Please tell us why you are blocking": "Veuillez nous dire pourquoi vous bloquez",
      "Blocking": "Blocage",
      "Languages": "Langues",
      "Block": "Bloquer",
      "Report": "Signaler",
      "Continue": "Continuer",
      "Why did you report this user?": "Pourquoi avez-vous signalé cet utilisateur ?",
      "Don't worry we won't tell them": "Ne vous inquiétez pas, nous ne leur dirons pas",
      "Please tell us why you are reporting": "Veuillez nous dire pourquoi vous signalez",
      "Reporting": "Signalement",
      "Send Gifts": "Envoyer des cadeaux",
      "Request Date": "Date de demande",
      "Ifsc Code": "Code IFSC",
      "Account Name": "Nom du compte",
      "pay by": "Payer par",
      "Amount": "Montant",
      "Number of coin": "Nombre de pièces",
      "Payout id": "ID de paiement",
      "User Chat": "Chat utilisateur",
      "Messages": "Messages",
      "Online now": "En ligne maintenant",
      "Select User": "Sélectionner un utilisateur",
      "Offline": "Hors ligne",
      "online": "en ligne",
      "No Any Match Profile...": "Aucun profil correspondant...",
      "Reset": "Réinitialiser",
      "No Any New Profile...": "Aucun nouveau profil...",
      "Start Your Search for the Perfect Partner": "Commencez votre recherche du partenaire parfait",
      "Under Review": "En cours de révision",
      "Unverified": "Non vérifié",
    }
  },
  de: {
    translation: {
      home: 'Startseite',
      about: 'Über uns',
      contact: 'Kontaktieren Sie uns',
      details: 'Detailseite',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Abmelden",
      "Account & Security": "Konto & Sicherheit",
      "Buy Coin": "Münzen kaufen",
      "Explore": "Erkunden",
      "Settings": "Einstellungen",
      "Wallet": "Geldbörse",
      "Edit": "Bearbeiten",
      "You're Activated Membersip": "Ihre Mitgliedschaft ist aktiviert",
      "Active": "Aktiv",
      "Enjoy premium and match anyway": "Genießen Sie Premium und matchen Sie trotzdem",
      "Is Verify": "Ist verifiziert",
      "Panding": "Ausstehend",
      "Upload Photo": "Foto hochladen",
      "persons Online": "Personen online",
      "There are": "Es gibt",
      "Loading...": "Lädt...",
      "Filter": "Filter",
      "Premium": "Premium",
      "Upgrade Now": "Jetzt upgraden",
      "Apply": "Anwenden",
      "Add": "Hinzufügen",
      "Add Your Favorite Photo": "Fügen Sie Ihr Lieblingsfoto hinzu",
      "Upload": "Hochladen",
      "shortly": "in Kürze",
      "selfies and will get back to you": "Selfies und wir melden uns bei Ihnen",
      "We are currently reviewing your": "Wir überprüfen derzeit Ihre",
      "Review": "Überprüfung",
      "Verification Under": "Verifizierung läuft",
      "No Any Passed Profiles...": "Keine übersprungenen Profile...",
      "No Add Any Favourite Profiles...": "Keine Favoritenprofile hinzugefügt...",
      "No Any User Like You...": "Keine Benutzer mögen Sie...",
      "No Any Match Profiles...": "Keine passenden Profile...",
      "Passed": "Übersprungen",
      "Favourite": "Favorit",
      "Like Me": "Mag mich",
      "New Match": "Neues Match",
      "Filter & Show": "Filtern & Anzeigen",
      "Verify Profile": "Profil verifizieren",
      "Distance Range": "Entfernungsbereich",
      "Age": "Alter",
      "Serach Preference": "Suchpräferenz",
      "Interests": "Interessen",
      "Langusges I Know": "Sprachen, die ich kenne",
      "Religion": "Religion",
      "Relationship Goals": "Beziehungsziele",
      "Update": "Aktualisieren",
      "Distance Preference": "Entfernungspräferenz",
      "Birthdate": "Geburtsdatum",
      "Password": "Passwort",
      "Mobile Number": "Handynummer",
      "Email": "E-Mail",
      "Nick Name": "Spitzname",
      "Update your personal photos here.": "Aktualisieren Sie hier Ihre persönlichen Fotos.",
      "Height": "Größe",
      "CM": "CM",
      "Bio": "Bio",
      "Gender": "Geschlecht",
      "No any Transaction...": "Keine Transaktionen...",
      "Transaction": "Transaktion",
      "Top-up": "Aufladen",
      "Total Balance": "Gesamtguthaben",
      "Coin Buying & Info": "Münzen kaufen & Info",
      "Withdraw": "Abheben",
      "Select Coin Package": "Münzpaket auswählen",
      "History": "Verlauf",
      "Your Coin": "Ihre Münzen",
      "Coins cannot be transferred to any users...": "Münzen können nicht an andere Benutzer übertragen werden...",
      "Coins can be withdrawn eith the described method only...": "Münzen können nur mit der beschriebenen Methode abgehoben werden...",
      "Coins are credited to your Coin balance only...": "Münzen werden nur Ihrem Münzguthaben gutgeschrieben...",
      "Coins can be used with all payment modes...": "Münzen können mit allen Zahlungsmethoden verwendet werden...",
      "Coins don't have any expiry date...": "Münzen haben kein Ablaufdatum...",
      "Coin can be used for sending gifts only...": "Münzen können nur zum Versenden von Geschenken verwendet werden...",
      "You need a minimum of 1000 coins to make a withdeawal...": "Sie benötigen mindestens 1000 Münzen, um eine Auszahlung vorzunehmen...",
      "The pepole you blocked are displayed here..": "Die von Ihnen blockierten Personen werden hier angezeigt.",
      "Blocked Users": "Blockierte Benutzer",
      "Get Started": "Loslegen",
      "Plans": "Pläne",
      "Number Of Coin": "Anzahl der Münzen",
      "Paypal": "PayPal",
      "BANK Transfer": "Banküberweisung",
      "Proceed": "Fortfahren",
      "Please Email ID": "Bitte E-Mail-ID eingeben",
      "Email ID": "E-Mail-ID",
      "Please Enter IFSC Code": "Bitte IFSC-Code eingeben",
      "IFSC Code": "IFSC-Code",
      "Please Enter Account Holder Name": "Bitte Kontoinhaber-Namen eingeben",
      "Account Holder Name": "Kontoinhaber-Name",
      "Please Enter Bank Name": "Bitte Bankname eingeben",
      "Bank Name": "Bankname",
      "Please Enter Account Number": "Bitte Kontonummer eingeben",
      "Account Number": "Kontonummer",
      "Please Enter UPI": "Bitte UPI eingeben",
      "UPI": "UPI",
      "Select Type": "Typ auswählen",
      "Please Enter Amount": "Bitte Betrag eingeben",
      "Coin History": "Münzverlauf",
      "Withdraw History": "Abhebungsverlauf",
      "Yes, Block": "Ja, blockieren",
      "Cancel": "Abbrechen",
      "You can unblock them anytime in Settings.": "Sie können die Blockierung jederzeit in den Einstellungen aufheben.",
      "They will not be notified if you block them.": "Sie werden nicht benachrichtigt, wenn Sie sie blockieren.",
      "They will not be able to find your profile and send you messages.": "Sie können Ihr Profil nicht finden und Ihnen keine Nachrichten senden.",
      "Acchcuu. Don't worry we won't tell them..": "Keine Sorge, wir werden es ihnen nicht sagen.",
      "Please tell us why you are blocking": "Bitte sagen Sie uns, warum Sie blockieren",
      "Blocking": "Blockieren",
      "Languages": "Sprachen",
      "Block": "Blockieren",
      "Report": "Melden",
      "Continue": "Fortfahren",
      "Why did you report this user?": "Warum haben Sie diesen Benutzer gemeldet?",
      "Don't worry we won't tell them": "Keine Sorge, wir werden es ihnen nicht sagen",
      "Please tell us why you are reporting": "Bitte sagen Sie uns, warum Sie melden",
      "Reporting": "Melden",
      "Send Gifts": "Geschenke senden",
      "Request Date": "Anfragedatum",
      "Ifsc Code": "IFSC-Code",
      "Account Name": "Kontoname",
      "pay by": "Bezahlen mit",
      "Amount": "Betrag",
      "Number of coin": "Anzahl der Münzen",
      "Payout id": "Auszahlungs-ID",
      "User Chat": "Benutzer-Chat",
      "Messages": "Nachrichten",
      "Online now": "Jetzt online",
      "Select User": "Benutzer auswählen",
      "Offline": "Offline",
      "online": "online",
      "No Any Match Profile...": "Keine passenden Profile...",
      "Reset": "Zurücksetzen",
      "No Any New Profile...": "Keine neuen Profile...",
      "Start Your Search for the Perfect Partner": "Starten Sie Ihre Suche nach dem perfekten Partner",
      "Under Review": "In Überprüfung",
      "Unverified": "Nicht verifiziert",
    }
  },
  ru: {
    translation: {
      home: 'Главная',
      about: 'О нас',
      contact: 'Свяжитесь с нами',
      details: 'Страница деталей',
      lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iusto harum tenetur magni laboriosam, minima fuga, sapiente culpa soluta totam non porro. Suscipit distinctio fugit veniam natus laborum ut aut?',
      "Log Out": "Выйти",
      "Account & Security": "Аккаунт и безопасность",
      "Buy Coin": "Купить монеты",
      "Explore": "Исследовать",
      "Settings": "Настройки",
      "Wallet": "Кошелек",
      "Edit": "Редактировать",
      "You're Activated Membersip": "Ваше членство активировано",
      "Active": "Активен",
      "Enjoy premium and match anyway": "Наслаждайтесь премиумом и находите пары в любом случае",
      "Is Verify": "Проверен",
      "Panding": "В ожидании",
      "Upload Photo": "Загрузить фото",
      "persons Online": "человек онлайн",
      "There are": "Сейчас",
      "Loading...": "Загрузка...",
      "Filter": "Фильтр",
      "Premium": "Премиум",
      "Upgrade Now": "Обновить сейчас",
      "Apply": "Применить",
      "Add": "Добавить",
      "Add Your Favorite Photo": "Добавьте свое любимое фото",
      "Upload": "Загрузить",
      "shortly": "вскоре",
      "selfies and will get back to you": "селфи, и мы свяжемся с вами",
      "We are currently reviewing your": "Мы сейчас проверяем ваши",
      "Review": "Проверка",
      "Verification Under": "Идет проверка",
      "No Any Passed Profiles...": "Нет пропущенных профилей...",
      "No Add Any Favourite Profiles...": "Нет добавленных избранных профилей...",
      "No Any User Like You...": "Никто не лайкнул вас...",
      "No Any Match Profiles...": "Нет совпадающих профилей...",
      "Passed": "Пропущен",
      "Favourite": "Избранное",
      "Like Me": "Лайкнули меня",
      "New Match": "Новое совпадение",
      "Filter & Show": "Фильтровать и показать",
      "Verify Profile": "Проверить профиль",
      "Distance Range": "Диапазон расстояния",
      "Age": "Возраст",
      "Serach Preference": "Предпочтения поиска",
      "Interests": "Интересы",
      "Langusges I Know": "Языки, которые я знаю",
      "Religion": "Религия",
      "Relationship Goals": "Цели отношений",
      "Update": "Обновить",
      "Distance Preference": "Предпочтение расстояния",
      "Birthdate": "Дата рождения",
      "Password": "Пароль",
      "Mobile Number": "Номер телефона",
      "Email": "Электронная почта",
      "Nick Name": "Псевдоним",
      "Update your personal photos here.": "Обновите свои личные фото здесь.",
      "Height": "Рост",
      "CM": "СМ",
      "Bio": "Био",
      "Gender": "Пол",
      "No any Transaction...": "Нет транзакций...",
      "Transaction": "Транзакция",
      "Top-up": "Пополнить",
      "Total Balance": "Общий баланс",
      "Coin Buying & Info": "Покупка монет и информация",
      "Withdraw": "Вывести",
      "Select Coin Package": "Выберите пакет монет",
      "History": "История",
      "Your Coin": "Ваши монеты",
      "Coins cannot be transferred to any users...": "Монеты нельзя передавать другим пользователям...",
      "Coins can be withdrawn eith the described method only...": "Монеты можно вывести только описанным способом...",
      "Coins are credited to your Coin balance only...": "Монеты зачисляются только на ваш баланс монет...",
      "Coins can be used with all payment modes...": "Монеты можно использовать со всеми способами оплаты...",
      "Coins don't have any expiry date...": "У монет нет срока действия...",
      "Coin can be used for sending gifts only...": "Монеты можно использовать только для отправки подарков...",
      "You need a minimum of 1000 coins to make a withdeawal...": "Вам нужно минимум 1000 монет для вывода...",
      "The pepole you blocked are displayed here..": "Здесь отображаются люди, которых вы заблокировали.",
      "Blocked Users": "Заблокированные пользователи",
      "Get Started": "Начать",
      "Plans": "Планы",
      "Number Of Coin": "Количество монет",
      "Paypal": "PayPal",
      "BANK Transfer": "Банковский перевод",
      "Proceed": "Продолжить",
      "Please Email ID": "Пожалуйста, введите ID электронной почты",
      "Email ID": "ID электронной почты",
      "Please Enter IFSC Code": "Пожалуйста, введите IFSC код",
      "IFSC Code": "IFSC код",
      "Please Enter Account Holder Name": "Пожалуйста, введите имя владельца счета",
      "Account Holder Name": "Имя владельца счета",
      "Please Enter Bank Name": "Пожалуйста, введите название банка",
      "Bank Name": "Название банка",
      "Please Enter Account Number": "Пожалуйста, введите номер счета",
      "Account Number": "Номер счета",
      "Please Enter UPI": "Пожалуйста, введите UPI",
      "UPI": "UPI",
      "Select Type": "Выберите тип",
      "Please Enter Amount": "Пожалуйста, введите сумму",
      "Coin History": "История монет",
      "Withdraw History": "История выводов",
      "Yes, Block": "Да, заблокировать",
      "Cancel": "Отмена",
      "You can unblock them anytime in Settings.": "Вы можете разблокировать их в любое время в настройках.",
      "They will not be notified if you block them.": "Они не получат уведомление, если вы их заблокируете.",
      "They will not be able to find your profile and send you messages.": "Они не смогут найти ваш профиль и отправить вам сообщения.",
      "Acchcuu. Don't worry we won't tell them..": "Не волнуйтесь, мы им не скажем.",
      "Please tell us why you are blocking": "Пожалуйста, скажите, почему вы блокируете",
      "Blocking": "Блокировка",
      "Languages": "Языки",
      "Block": "Заблокировать",
      "Report": "Пожаловаться",
      "Continue": "Продолжить",
      "Why did you report this user?": "Почему вы пожаловались на этого пользователя?",
      "Don't worry we won't tell them": "Не волнуйтесь, мы им не скажем",
      "Please tell us why you are reporting": "Пожалуйста, скажите, почему вы жалуетесь",
      "Reporting": "Жалоба",
      "Send Gifts": "Отправить подарки",
      "Request Date": "Дата запроса",
      "Ifsc Code": "IFSC код",
      "Account Name": "Имя счета",
      "pay by": "Оплатить через",
      "Amount": "Сумма",
      "Number of coin": "Количество монет",
      "Payout id": "ID выплаты",
      "User Chat": "Чат пользователя",
      "Messages": "Сообщения",
      "Online now": "Сейчас онлайн",
      "Select User": "Выбрать пользователя",
      "Offline": "Не в сети",
      "online": "онлайн",
      "No Any Match Profile...": "Нет совпадающих профилей...",
      "Reset": "Сбросить",
      "No Any New Profile...": "Нет новых профилей...",
      "Start Your Search for the Perfect Partner": "Начните поиск идеального партнера",
      "Under Review": "На проверке",
      "Unverified": "Не проверен",
    }
  },
};

const savedLanguage = localStorage.getItem('i18nextLng') ||
                      sessionStorage.getItem('I18') ||
                      'en';

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: savedLanguage,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    },
    detection: {
      order: ['localStorage', 'sessionStorage', 'navigator'],
      lookupLocalStorage: 'i18nextLng',
      lookupSessionStorage: 'I18',
      caches: ['localStorage', 'sessionStorage']
    }
  });

document.documentElement.lang = savedLanguage;
document.documentElement.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr';

i18n.on('languageChanged', (lng) => {
  localStorage.setItem('i18nextLng', lng);
  sessionStorage.setItem('I18', lng);
  document.documentElement.lang = lng;
  document.documentElement.dir = lng === 'ar' ? 'rtl' : 'ltr';
});

export default i18n;
